project:
  type: website

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: page 1.qmd
        text: Page 1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

