project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - page1.qmd
      - what_is_hcl.qmd
      - about.qmd
  page-footer:
    left: 
      - text: "Hello!"

format:
  html:
    self-contained: true
    code-fold: true
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    
editor: visual

