project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  comments: 
    utterances: 
      repo: quarto-dev/quarto-web
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Pages"
        contents:
          - page1.qmd
          - href: tidy_wwc.qmd
            text: "FIFA Women's World Cup"
      - section: "Colorful Bubbles"
        contents: 
          - href: colorful_circles.qmd
            text: "Generation"
          - href: colorcir_analysis.qmd
            text: "Analysis"
      - section: "Notes"
        contents: 
          - what_is_hcl.qmd
          - conditional_probability.qmd
  navbar:
    left:
      - href: index.qmd
        text: Home
      - page1.qmd
      - href: tidy_wwc.qmd
        text: Tidy Tuesday
        icon: bar-chart
      - what_is_hcl.qmd
      - href: about.qmd
        icon: file-person
  # page-footer:
  #   left: 
  #     - text: "Hello!"

format:
  html:
    # self-contained: true
    embed-resources: true
    code-fold: true
    code-summary: 'Show code'
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    
editor: visual

execute: 
  cache: true
  messages: false
  warning: false

