project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Pages"
        contents:
          - page1.qmd
          - tidy_wwc.qmd
      - section: "Colorful Circles"
        contents: 
          - href: colorful_circles.qmd
            text: "Generation"
      - section: "Notes"
        contents: 
          - what_is_hcl.qmd
          - conditional_probability.qmd
          
  navbar:
    left:
      - href: index.qmd
        text: Home
      - page1.qmd
      - href: tidy_wwc.qmd
        text: Tidy Tuesday
        icon: bar-chart
      - what_is_hcl.qmd
      - href: about.qmd
        icon: file-person
  page-footer:
    left: 
      - text: "Hello!"

format:
  html:
    # self-contained: true
    embed-resources: true
    code-fold: true
    code-summary: 'Show code'
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    
editor: visual

execute: 
  cache: true
  messages: false
  warning: false

