project:
  type: website
  output-dir: docs

website:
  comments: 
    utterances: 
      repo: quarto-dev/quarto-web
      theme: dark-blue
      issue-term: title
  title: "Portfolio"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Home Energy Usage"
        contents:
          href: eulr_analysis.qmd
          text: "Impact of COVID-19"
      - section: "Colorful Bubbles"
        contents:
          - href: colorful_circles.qmd
            text: "Generation"
          - href: colorcir_analysis.qmd
            text: "Analysis"
      - section: "Other pages"
        contents:
          - page1.qmd
          - href: tidy_wwc.qmd
            text: "FIFA Women's World Cup"
      - section: "Notes"
        contents:
          - what_is_hcl.qmd
          - conditional_probability.qmd
          - the_logo.qmd
  navbar:
    logo: data/logo.png
    left:
      - href: eulr_analysis.qmd
        text: HEMS
      - page1.qmd
      - href: tidy_wwc.qmd
        text: Tidy Tuesday
        icon: bar-chart
      - href: about.qmd
        icon: file-person
  page-footer:
    left:
      - text: "Hello!"

format:
  html:
    # self-contained: true
    # embed-resources: true
    code-fold: true
    code-summary: 'Show code'
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    
editor: visual

execute: 
  cache: false
  messages: false
  warning: false

